# --- Defaults ---

# --- marl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "cluster" # Environment name
env_args: { } # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 8 # Number of episodes to test for
# test_interval: 50000 # Test after {} timesteps have passed
test_interval: 5000 # Test after {} timesteps have passed

test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 10000 # Log summary of stats after every {} timesteps
runner_log_interval: 2000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 2000 # Log training stats every {} timesteps
t_max: 10000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: False # Log results to tensorboard
save_model: False # Save the models to disk
save_model_interval: 2000000 # Save models after this many timesteps
checkpoint_path: "" # Load a checkpoint from this path
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 32 # Size of the replay buffer
# lr: 0.00001 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha - RMSProp 优化算法的衰减系数，用于调整梯度的移动平均值。较小的 alpha 值使得移动平均值对梯度变化更加敏感。
optim_eps: 0.00001 # RMSProp epsilon - RMSProp 优化算法中用于防止除零错误的小值。它是一个小的正数，通常设置为较小的常数（如 1e-8）。
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm - 用于防止梯度爆炸问题的梯度范数的最大值。如果梯度的 L2 范数超过这个阈值，它们将被缩放到指定的范围内。

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: False # Include the agent's one_hot id in the observation
# obs_agent_id: False
# obs_last_action: True # Include the agent's last action (one_hot) in the observation
obs_last_action: False

# --- Experiment running params ---
repeat_id: 1
label: "default_label"

run: "default"
# run: "two_sample"
# run: "transfer"
is_two_sample: True
highreward_sample: 0.5
