# 这是一个 yaml 配置文件，存储环境的配置参数
# 参考教程：https://zhuanlan.zhihu.com/p/145173920
env: cluster

env_args:

  # 环境参数
  map_name: "large_map"
  slot_num: 100
  slot_length: 5.0
  uav_num: 6
  map_length: 40
  map_width: 30
  map_height: 5
  penalty: -5  # 无人机非法动作的惩罚项
  channel_num: 4  # 观测的通道数
  specify_ue_pos: True
  ue_pos_file: "src/envs/env_1/ue_pos_config/ue_pos_large_map.csv"
  ue_cluster_file: "src/envs/env_1/cluster_config/clusters_large_map.csv"
  obs_list_file: "src/envs/env_1/obstacle_config/obs_list_large_map.csv"
  use_onehot: True  # 在向量观测 / 状态中使用 OneHot 编码
  use_novelty: True  # 在奖励函数中包含 Novelty 项
  use_hybrid_novelty: False

  # UE 参数
  ue:
    cluster_num: 6
    num_in_a_cluster: 72
    max_cluster_size: 3
    cluster_cover_threshold: 0.6
    specify_cluster_centers: False
    cluster_centers:

  # UAV 参数
  uav:
    obs_radius: [ 1.0, 1.0, 2.0, 1.0, 1.0 ]
    cover_radius: [ 1.0, 1.5, 2.0, 1.5, 1.0 ]
    action_space:
      - [ # 离散角度
        0.0,
        0.7853981633974483,   # pi / 4
        1.5707963267948966,   # pi / 2
        2.356194490192345,    # 3pi / 4
        3.141592653589793,    # pi
        3.9269908169872414,   # 5pi / 4
        4.71238898038469,     # 3pi / 2
        5.497787143782138     # 7pi / 4
      ]
      - [ 0, 1 ]           # 离散水平位移
      - [ -1, 0, 1 ]            # 离散垂直位移
    horizon_speed: 1.0
    vertical_speed: 1.0
    max_energy: 100
    max_serve_capacity: 40
    epsilon: [ 0.6, 0.7, 0.3, 0.1, 0.01 ]  # 能量相关的超参数
    action_size: 27  # 动作空间大小
    max_obs_radius: 2
    obs_radius_change: False # 无人机的观测半径是否随高度变化
    specify_initial_pos: True
    initial_pos:
      - [ 18, 15, 1 ]
      - [ 20, 15, 1 ]
      - [ 22, 15, 1 ]
      - [ 19, 13, 1 ]
      - [ 21, 13, 1 ]
      - [ 23, 13, 1 ]
      - [ 15, 20, 1 ]
      - [ 25, 13, 1 ]
#      - [35, 15, 1]
#      - [3, 15, 3]
#      - [15, 10, 1]
#      - [20, 15, 3]
#      - [25, 1, 1]
#      - [30, 27, 3]
