# 这是一个 yaml 配置文件，存储环境的配置参数
# 参考教程：https://zhuanlan.zhihu.com/p/145173920
env: multiObject

env_args:
  # 环境参数
  map_name: "multi_object"
  seed: 2024111
  map_length: 1000
  map_width: 1000
  slot_num: 100
  penalty: -3
  tcs_pos: [ 0, 0 ]  # 充电站位置

  # UE 参数
  ue:
    num: 100
    max_payload: 16
    max_generate_time: 50

  # UAV 参数
  uav:
    specify_initial_pos: True
    initial_pos: [500, 500]
    speed: 20
    height: 10
    max_energy: 1.0e5
    action_space:
      - [ 0, 0 ]
      - [ 100, 0.0 ]
      - [ 100, 0.7853981633974483 ]   # pi / 4
      - [ 100, 1.5707963267948966 ]   # pi / 2
      - [ 100, 2.356194490192345 ]    # 3pi / 4
      - [ 100, 3.141592653589793 ]    # pi
      - [ 100, 3.9269908169872414 ]   # 5pi / 4
      - [ 100, 4.71238898038469 ]     # 3pi / 2
      - [ 100, 5.497787143782138 ]    # 7pi / 4
    low_power_thresh: 0.2             # 低电量阈值比例
    low_tr_thresh: 10                 # 低于此传输速率的用户不进行数据传输
    # 公式中的超参数
    # (8)
    B: 1.0e7                          # 链路带宽
    P_m: 5                            # SN 的传输功率
    beta_0: -60                       # 参考距离上的功率增益
    sigma_square: -110                # 接收器的白高斯噪声功率
    a_1: 0                            # logistic 回归参数
    a_2: 1                            # logistic 回归参数
    b_1: -4.3221                      # logistic 回归参数
    b_2: 6.075                        # logistic 回归参数
    # (13)
    eta: 0.8                          # 能量转换效率
    P_0: 100                          # 激光功率
    tau: 5                            # 时隙长度
    A: 0.05                           # 激光接收器的面积
    V: 0.2                            # 接收器光学效率
    alpha: 1.0e-6                     # 单位米内的链路衰减效率
    D: 0.05                           # 激光束的尺寸
    beta: 3.4e-5                      # 激光束的角度扩展
    # (16)
    P_blade: 79.86                    # 悬停时的叶片剖面功率
    P_i: 88.63                        # 悬停时的叶片诱导功率
    U_tip: 120                        # 旋翼叶尖速度
    v_0: 4.03                         # 悬停时的平均诱导速度
    d_0: 0.6                          # 机身阻力比
    rho: 1.225                        # 空气密度
    s: 0.05                           # 转子坚固度
    A_roter: 0.503                    # 转子盘面积
    P_c: 0.2                          # 无人机传输功率
